version: '3.8'
services:
    db:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=express-starter
        volumes:
            - /home/ivsheva/volumes/express-starter-db:/var/lib/postgresql/data
